name: Vulnerability
description: Report a vulnerability in the project
labels:
  - vulnerability
title: "[Vulnerability] "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a vulnerability in the project. Please fill out the information below to help us better understand the issue.
  - type: input
    id: vulnerability-title
    attributes:
      label: Vulnerability Title
      description: A short title for the vulnerability
      placeholder: Vulnerability Title
    validations:
      required: true
  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: A description of the vulnerability
      placeholder: Vulnerability Description
    validations:
      required: true
  - type: textarea
    id: vulnerability-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the vulnerability
      placeholder: Steps to Reproduce
    validations:
      required: true
  - type: textarea
    id: vulnerability-impact
    attributes:
      label: Impact
      description: The impact of the vulnerability
      placeholder: Impact
    validations:
      required: true
  - type: textarea
    id: vulnerability-remediation
    attributes:
      label: Remediation
      description: The remediation steps for the vulnerability
      placeholder: Remediation
    validations:
      required: true
  - type: textarea
    id: vulnerability-references
    attributes:
      label: References
      description: References for the vulnerability
      placeholder: References
    validations:
      required: true
  - type: textarea
    id: vulnerability-credit
    attributes:
      label: Credit
      description: Credit for the vulnerability
      placeholder: Credit
    validations:
      required: true